version 1.0

## Copyright Broad Institute, 2017
##
## This WDL workflow runs GATK4 Mutect 2 on a single tumor-normal pair or on a single tumor sample,
## and performs additional filtering.
##
## Main requirements/expectations :
## - One analysis-ready BAM file (and its index) for each sample
##
## Description of inputs:
##
## ** Runtime **
## gatk_docker: docker image to use for GATK 4 Mutect2
## preemptible: how many preemptions to tolerate before switching to a non-preemptible machine (on Google)
## max_retries: how many times to retry failed tasks -- very important on the cloud when there are transient errors
## gatk_override: (optional) local file or Google bucket path to a GATK 4 java jar file to be used instead of the GATK 4 jar
##                in the docker image.  This must be supplied when running in an environment that does not support docker
##                (e.g. SGE cluster on a Broad on-prem VM)
##                  
##                  Note: 1/21/2026 I (Chris Reynolds) have removed gatk_override from most tasks and the workflow itself. We are running on DNA nexus in docker and shouldn't have need of a jar override.
##
## ** Workflow options **
## intervals: genomic intervals (will be used for scatter)
## scatter_count: number of parallel jobs to generate when scattering over intervals
## m2_extra_args, m2_extra_filtering_args: additional arguments for Mutect2 calling and filtering (optional)
## split_intervals_extra_args: additional arguments for splitting intervals before scattering (optional)
## run_orientation_bias_mixture_model_filter: (optional) if true, filter orientation bias sites with the read orientation artifact mixture model.
##
## ** Primary inputs **
## ref_fasta, ref_fai, ref_dict: reference genome, index, and dictionary
## tumor_reas, tumor_reads_index: BAM and index for the tumor sample
## normal_reads, normal_reads_index: BAM and index for the normal sample
##
## ** Primary resources ** (optional but strongly recommended)
## pon, pon_idx: optional panel of normals (and its index) in VCF format containing probable technical artifacts (false positves)
## gnomad, gnomad_idx: optional database of known germline variants (and its index) (see http://gnomad.broadinstitute.org/downloads)
## variants_for_contamination, variants_for_contamination_idx: VCF of common variants (and its index)with allele frequencies for calculating contamination
##
## ** Secondary resources ** (for optional tasks)
## realignment_index_bundle: resource for FilterAlignmentArtifacts, which runs if and only if it is specified.  Generated by BwaMemIndexImageCreator.
##
## Outputs :
## - One VCF file and its index with primary filtering applied; secondary filtering if requested; a bamout.bam
##   file of reassembled reads if requested
##
## Cromwell version support
## - Successfully tested on v34
##
## LICENSING :
## This script is released under the GATK source code license (Apache 2.0) (see LICENSE in
## https://github.com/broadinstitute/gatk). Note however that the programs it calls may
## be subject to different licenses. Users are responsible for checking that they are
## authorized to run all programs before running this script.  Please see the docker
## pages at https://hub.docker.com/r/broadinstitute/* for detailed licensing information
## pertaining to the included programs.

struct Runtime {
    String gatk_docker
    Int max_retries
    Int cpu
    Int machine_mem
    Int command_mem
    Int disk
    Int boot_disk_size
}

workflow Mutect2 {
    input {
        # basic inputs
        File? intervals
        File? masked_intervals
        File ref_fasta
        File ref_fai
        File ref_dict
        File tumor_reads
        File tumor_reads_index
        File? normal_reads
        File? normal_reads_index

        # optional but usually recommended resources
        File? pon
        File? pon_idx
        File? gnomad
        File? gnomad_idx
        File? variants_for_contamination
        File? variants_for_contamination_idx

        # extra arguments
        String? m2_extra_args
        String? m2_extra_filtering_args
        String? getpileupsummaries_extra_args
        String? split_intervals_extra_args

        # additional modes and outputs
        File? realignment_index_bundle
        String? realignment_extra_args
        File? dragstr_model
        Boolean run_orientation_bias_mixture_model_filter = false
        Boolean make_bamout = false
        Boolean compress_vcfs = false
        File? gga_vcf
        File? gga_vcf_idx
        Boolean make_permutect_training_dataset = false
        Boolean make_permutect_test_dataset = false
        File? permutect_training_dataset_truth_vcf
        File? permutect_training_dataset_truth_vcf_idx
        File? permutect_test_dataset_truth_vcf
        File? permutect_test_dataset_truth_vcf_idx
        Boolean skip_filtering = false


        # runtime
        String gatk_docker = "broadinstitute/gatk:4.6.2.0"
        Int scatter_count
        Int small_task_cpu = 2
        Int small_task_mem = 4
        Int small_task_disk = 100
        Int large_task_cpu = 4
        Int large_task_mem = 16
        Int large_task_disk = 250
        Float disk_padding_factor = 1.5 #factor by which to multiply estimated disk usage for padding. 1.1= 110%% of estimate for example.
        Float java_heap_fraction = 0.8 #fraction of memory to allocate to java heap
    }
    
    #Pulls the sample name from the tumor bam file name
    String tumor_sample_name = basename(tumor_reads,".bam")

    # Disk sizes used for dynamic sizing
    Int ref_size = ceil(size(ref_fasta, "GB") + size(ref_dict, "GB") + size(ref_fai, "GB"))
    Int tumor_reads_size = ceil(size(tumor_reads, "GB") + size(tumor_reads_index, "GB"))
    Int gnomad_vcf_size = if defined(gnomad) then ceil(size(gnomad, "GB")) else 0
    Int normal_reads_size = if defined(normal_reads) then ceil(size(normal_reads, "GB") + size(normal_reads_index, "GB")) else 0

    #m2 scatter disk size
    Int m2_per_scatter_disk_size_raw =
        ceil(((tumor_reads_size + normal_reads_size) + ref_size + gnomad_vcf_size) * disk_padding_factor)

    Int m2_per_scatter_disk_size =
        if (m2_per_scatter_disk_size_raw > 100) then m2_per_scatter_disk_size_raw else 100

    #m2 scatter memory size
    Int m2_per_scatter_memory_size_raw = floor(m2_per_scatter_disk_size / 2.0)

    Int m2_per_scatter_memory_size =
        if (m2_per_scatter_memory_size_raw > 8) then m2_per_scatter_memory_size_raw else 8

    #m2 heap size
    Int m2_per_scatter_heap_size = ceil(m2_per_scatter_memory_size * java_heap_fraction * 1000)

    #standard machine heap sizes
    Int small_task_heap_size = ceil(small_task_mem * java_heap_fraction * 1000)
    Int large_task_heap_size = ceil(large_task_mem * java_heap_fraction * 1000)

    call SplitIntervals {
        input:
            intervals = intervals,
            masked_intervals = masked_intervals,
            ref_fasta = ref_fasta,
            ref_fai = ref_fai,
            ref_dict = ref_dict,
            scatter_count = scatter_count,
            split_intervals_extra_args = split_intervals_extra_args,
            gatk_docker = gatk_docker,
            cpu = small_task_cpu,
            mem = small_task_mem,
            disk = small_task_disk,
            heap_size = small_task_heap_size

    }

    scatter (subintervals in SplitIntervals.interval_files ) {
        call M2 {
            input:
                intervals = subintervals,
                ref_fasta = ref_fasta,
                ref_fai = ref_fai,
                ref_dict = ref_dict,
                tumor_reads = tumor_reads,
                tumor_reads_index = tumor_reads_index,
                normal_reads = normal_reads,
                normal_reads_index = normal_reads_index,
                pon = pon,
                pon_idx = pon_idx,
                gnomad = gnomad,
                gnomad_idx = gnomad_idx,
                m2_extra_args = m2_extra_args,
                getpileupsummaries_extra_args = getpileupsummaries_extra_args,
                variants_for_contamination = variants_for_contamination,
                variants_for_contamination_idx = variants_for_contamination_idx,
                dragstr_model = dragstr_model,
                make_bamout = make_bamout,
                run_ob_filter = run_orientation_bias_mixture_model_filter,
                compress_vcfs = compress_vcfs,
                gga_vcf = gga_vcf,
                gga_vcf_idx = gga_vcf_idx,
                make_permutect_training_dataset = make_permutect_training_dataset,
                make_permutect_test_dataset = make_permutect_test_dataset,
                permutect_training_dataset_truth_vcf = permutect_training_dataset_truth_vcf,
                permutect_training_dataset_truth_vcf_idx = permutect_training_dataset_truth_vcf_idx,
                permutect_test_dataset_truth_vcf = permutect_test_dataset_truth_vcf,
                permutect_test_dataset_truth_vcf_idx = permutect_test_dataset_truth_vcf_idx,
                gatk_docker = gatk_docker,
                cpu = large_task_cpu,
                mem = m2_per_scatter_memory_size,
                disk = m2_per_scatter_disk_size,
                heap_size = m2_per_scatter_heap_size,
                tumor_sample_name = tumor_sample_name
               
        }
    }

    if (run_orientation_bias_mixture_model_filter && (!skip_filtering)) {
        call LearnReadOrientationModel {
            input:
                f1r2_tar_gz = M2.f1r2_counts,
                gatk_docker = gatk_docker,
                cpu = large_task_cpu,
                mem = large_task_mem,
                disk = large_task_disk,
                heap_size = large_task_heap_size
        }
    }

    call MergeVCFs {
        input:
            input_vcfs = M2.unfiltered_vcf,
            input_vcf_indices = M2.unfiltered_vcf_idx,
            compress_vcfs = compress_vcfs,
            gatk_docker = gatk_docker,
            cpu = small_task_cpu,
            mem = small_task_mem,
            disk = small_task_disk,
            heap_size = small_task_heap_size,
            tumor_sample_name = tumor_sample_name

    }

    if (make_bamout) {
        call MergeBamOuts {
            input:
                ref_fasta = ref_fasta,
                ref_fai = ref_fai,
                ref_dict = ref_dict,
                bam_outs = M2.output_bamOut,
                gatk_docker = gatk_docker,
                cpu = large_task_cpu,
                mem = large_task_mem,
                disk = large_task_disk,
                heap_size = large_task_heap_size,
                tumor_sample_name = tumor_sample_name

        }
    }

    call MergeStats { 
        input: 
            stats = M2.stats, 
            gatk_docker = gatk_docker,
            cpu = small_task_cpu,
            mem = small_task_mem,
            disk = small_task_disk,
            heap_size = small_task_heap_size
    }

    # When generating Permutect test data we need the minor allele fraction (MAF) segmentation from CalculateContamination,
    # even if we are skipping filtering.  Note also that we run CalculateContamination witht he normal as a "tumor"
    # in order to get normal MAF segments.
    if (defined(variants_for_contamination) && (make_permutect_test_dataset || (!skip_filtering))) {
        call MergePileupSummaries as MergeTumorPileups {
            input:
                input_tables = flatten(M2.tumor_pileups),
                output_name = "tumor-pileups",
                ref_dict = ref_dict,
                gatk_docker = gatk_docker,
                cpu = small_task_cpu,
                mem = small_task_mem,
                disk = small_task_disk,
                heap_size = small_task_heap_size
        }

        if (defined(normal_reads)){
            call MergePileupSummaries as MergeNormalPileups {
                input:
                    input_tables = flatten(M2.normal_pileups),
                    output_name = "normal-pileups",
                    ref_dict = ref_dict,
                    gatk_docker = gatk_docker,
                    cpu = small_task_cpu,
                    mem = small_task_mem,
                    disk = small_task_disk,
                    heap_size = small_task_heap_size

            }

            if (make_permutect_test_dataset) {
                call CalculateContamination as GetNormalMAFSegments {
                    input:
                        tumor_pileups = select_first([MergeNormalPileups.merged_table]),
                        gatk_docker = gatk_docker,
                        cpu = large_task_cpu,
                        mem = large_task_mem,
                        disk = large_task_disk,
                        heap_size = large_task_heap_size

                }
            }
        }

        call CalculateContamination {
            input:
                tumor_pileups = MergeTumorPileups.merged_table,
                normal_pileups = MergeNormalPileups.merged_table,
                gatk_docker = gatk_docker,
                cpu = large_task_cpu,
                mem = large_task_mem,
                disk = large_task_disk,
                heap_size = large_task_heap_size

        }
    }

    if (make_permutect_training_dataset) {
        call Concatenate as ConcatenatePermutectTrainingData {
            input:
                input_files = M2.permutect_training_dataset,
                gatk_docker = gatk_docker,
                cpu = small_task_cpu,
                mem = small_task_mem,
                disk = small_task_disk

        }
    }

    if (make_permutect_test_dataset) {
        call Concatenate as ConcatenatePermutectTestData {
            input:
                input_files = M2.permutect_test_dataset,
                gatk_docker = gatk_docker,
                cpu = small_task_cpu,
                mem = small_task_mem,
                disk = small_task_disk
        }
    }

    if (!skip_filtering) {
        call Filter {
            input:
                ref_fasta = ref_fasta,
                ref_fai = ref_fai,
                ref_dict = ref_dict,
                intervals = intervals,
                unfiltered_vcf = MergeVCFs.merged_vcf,
                unfiltered_vcf_idx = MergeVCFs.merged_vcf_idx,
                compress_vcfs = compress_vcfs,
                mutect_stats = MergeStats.merged_stats,
                contamination_table = CalculateContamination.contamination_table,
                maf_segments = CalculateContamination.maf_segments,
                artifact_priors_tar_gz = LearnReadOrientationModel.artifact_prior_table,
                m2_extra_filtering_args = m2_extra_filtering_args,
                gatk_docker = gatk_docker,
                cpu = large_task_cpu,
                mem = large_task_mem,
                disk = large_task_disk,
                heap_size = large_task_heap_size,
                tumor_sample_name = tumor_sample_name
        }

        if (defined(realignment_index_bundle)) {
            call FilterAlignmentArtifacts {
                input:
                    ref_fasta = ref_fasta,
                    ref_fai = ref_fai,
                    ref_dict = ref_dict,
                    reads = tumor_reads,
                    reads_index = tumor_reads_index,
                    realignment_index_bundle = select_first([realignment_index_bundle]),
                    realignment_extra_args = realignment_extra_args,
                    compress_vcfs = compress_vcfs,
                    input_vcf = Filter.filtered_vcf,
                    input_vcf_idx = Filter.filtered_vcf_idx,
                    gatk_docker = gatk_docker,
                    cpu = large_task_cpu,
                    mem = large_task_mem,
                    disk = large_task_disk,
                    heap_size = large_task_heap_size,
                    tumor_sample_name = tumor_sample_name
            }
        }
    }

    output {
        File output_vcf = select_first([FilterAlignmentArtifacts.filtered_vcf, Filter.filtered_vcf, MergeVCFs.merged_vcf])
        File output_vcf_idx = select_first([FilterAlignmentArtifacts.filtered_vcf_idx, Filter.filtered_vcf_idx,MergeVCFs.merged_vcf_idx])
        File? filtering_stats = Filter.filtering_stats
        File mutect_stats = MergeStats.merged_stats
        File? contamination_table = CalculateContamination.contamination_table

        File? bamout = MergeBamOuts.merged_bam_out
        File? bamout_index = MergeBamOuts.merged_bam_out_index
        File? maf_segments = CalculateContamination.maf_segments
        File? normal_maf_segments = GetNormalMAFSegments.maf_segments
        File? read_orientation_model_params = LearnReadOrientationModel.artifact_prior_table
        File? permutect_training_dataset = ConcatenatePermutectTrainingData.concatenated
        File? permutect_test_dataset = ConcatenatePermutectTestData.concatenated
        File permutect_contigs_table = select_first(M2.permutect_contigs_table)
        File permutect_read_groups_table = select_first(M2.permutect_read_groups_table)
    }
}

task SplitIntervals {
    input {
      File? intervals
      File? masked_intervals
      File ref_fasta
      File ref_fai
      File ref_dict
      Int scatter_count
      String? split_intervals_extra_args
      
      # runtime
      String gatk_docker
      Int cpu
      Int mem
      Int disk
      Int heap_size
    }

    command <<<
        set -e

        mkdir interval-files
        gatk --java-options "-Xmx~{heap_size}m" SplitIntervals \
            -R ~{ref_fasta} \
            ~{if defined(intervals) then "-L " + select_first([intervals]) else ""} \
            ~{if defined(masked_intervals) then "-XL " + select_first([masked_intervals]) else ""} \
            -scatter ~{scatter_count} \
            -O interval-files \
            ~{split_intervals_extra_args}
        cp interval-files/*.interval_list .
    >>>

    runtime {
        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        Array[File] interval_files = glob("*.interval_list")
    }
}

task M2 {
    input {
        File? intervals
        File ref_fasta
        File ref_fai
        File ref_dict
        File tumor_reads
        File tumor_reads_index
        File? normal_reads
        File? normal_reads_index
        File? pon
        File? pon_idx
        File? gnomad
        File? gnomad_idx
        String? m2_extra_args
        String? getpileupsummaries_extra_args
        Boolean make_bamout
        Boolean run_ob_filter
        Boolean compress_vcfs
        File? gga_vcf
        File? gga_vcf_idx
        File? variants_for_contamination
        File? variants_for_contamination_idx
        File? dragstr_model

        Boolean make_permutect_training_dataset = false
        Boolean make_permutect_test_dataset = false
        File? permutect_training_dataset_truth_vcf
        File? permutect_training_dataset_truth_vcf_idx
        File? permutect_test_dataset_truth_vcf
        File? permutect_test_dataset_truth_vcf_idx
        String tumor_sample_name

        # runtime
        String gatk_docker
        Int mem
        Int disk
        Int cpu
        Int heap_size
    }

    #fetches the sample name from the name of the tumor bam file
    

    String output_vcf = tumor_sample_name + if compress_vcfs then ".vcf.gz" else ".vcf"
    String output_vcf_idx = output_vcf + if compress_vcfs then ".tbi" else ".idx"

    String output_stats = output_vcf + ".stats"

    String tumor_pileups_table = tumor_sample_name + "-tumor-pileups.table"
    String normal_pileups_table = tumor_sample_name + "-normal-pileups.table"
    String bamout_name = tumor_sample_name + "-bamout.bam"
    String f1r2_name = tumor_sample_name + "-f1r2.tar.gz"
    String training_dataset_name = tumor_sample_name + "-training-dataset.txt"
    String test_dataset_name = tumor_sample_name + "-test-dataset.txt"
    String contigs_table_name = "contigs.table"
    String read_groups_table_name = "read-groups.table"

    parameter_meta{
        intervals: {localization_optional: true}
        ref_fasta: {localization_optional: true}
        ref_fai: {localization_optional: true}
        ref_dict: {localization_optional: true}
        tumor_reads: {localization_optional: true}
        tumor_reads_index: {localization_optional: true}
        normal_reads: {localization_optional: true}
        normal_reads_index: {localization_optional: true}
        pon: {localization_optional: true}
        pon_idx: {localization_optional: true}
        gnomad: {localization_optional: true}
        gnomad_idx: {localization_optional: true}
        gga_vcf: {localization_optional: true}
        gga_vcf_idx: {localization_optional: true}
        variants_for_contamination: {localization_optional: true}
        variants_for_contamination_idx: {localization_optional: true}
        permutect_training_dataset_truth_vcf: {localization_optional: true}
        permutect_training_dataset_truth_vcf_idx: {localization_optional: true}
    }

    command <<<
        set -euo pipefail
        ############################################################################################
        #These blocks are for debugging purposes
        echo "===== DEBUG: basic context ====="
        pwd
        whoami
        hostname
        date

        echo "===== DEBUG: directory listing ====="
        ls -lah

        echo "===== DEBUG: gnomAD files ====="
        echo "gnomad: ~{gnomad}"
        echo "gnomad_idx: ~{gnomad_idx}"

        ls -lah ~{gnomad} || true
        ls -lah ~{gnomad_idx} || true

        echo "===== DEBUG: contamination VCF ====="
        echo "variants_for_contamination: ~{variants_for_contamination}"
        echo "variants_for_contamination_idx: ~{variants_for_contamination_idx}"

        ls -lah ~{variants_for_contamination} || true
        ls -lah ~{variants_for_contamination_idx} || true

        echo "===== DEBUG: contamination VCF ====="
        echo "pon: ~{pon}"
        echo "pon_idx: ~{pon_idx}"

        ls -lah ~{pon} || true
        ls -lah ~{pon_idx} || true

        echo "normal bam: ~{normal_reads}"
        echo "normal bai: ~{normal_reads_index}"

        ls -lah ~{normal_reads}
        ls -lah ~{normal_reads_index}

        echo "tumor bam: ~{tumor_reads}"
        echo "tumor bai: ~{tumor_reads_index}"

        ls -lah ~{tumor_reads}
        ls -lah ~{tumor_reads_index}

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true

        ############################################################################################

        # We need to create these files regardless, even if they stay empty
        touch ~{bamout_name}
        touch ~{f1r2_name}
        touch ~{training_dataset_name}
        touch ~{test_dataset_name}
        touch ~{contigs_table_name}
        touch ~{read_groups_table_name}

        if [[ ! -n "~{normal_reads}" ]]; then
            gatk --java-options "-Xmx~{heap_size}m" GetSampleName -R ~{ref_fasta} -I ~{normal_reads} -O normal_names.txt -encode
            # add "-normal " to the start of each line and " " to the end, then remove newlines
            # to get -normal sample1 -normal sample2 etc
            normal_sample_line=`awk '{ print "-normal", $0 }' normal_names.txt | tr '\n' ' '`
        fi

        gatk --java-options "-Xmx~{heap_size}m" Mutect2 \
            -R ~{ref_fasta} \
            -I ~{tumor_reads} \
            ~{if defined(normal_reads) then "-I " + select_first([normal_reads]) else ""} \
            $normal_sample_line \
            ~{if defined(gnomad) then "--germline-resource " + gnomad else ""} \
            ~{if defined(pon) then "-pon " + pon else ""} \
            ~{if defined(intervals) then "-L " + select_first([intervals]) else ""} \
            ~{if defined(gga_vcf) then "--alleles " + gga_vcf else ""} \
            ~{if defined(dragstr_model) then "--dragstr-params-path " + dragstr_model else ""} \
            -O "~{output_vcf}" \
            ~{if make_bamout then "--bam-output " + bamout_name else ""} \
            ~{if run_ob_filter then "--f1r2-tar-gz " + f1r2_name else ""} \
            ~{if make_permutect_training_dataset then "--permutect-training-dataset " + training_dataset_name else ""}
            ~{if make_permutect_test_dataset then "--permutect-test-dataset " + test_dataset_name else ""}  
            ~{if defined(permutect_training_dataset_truth_vcf) then "--permutect-training-truth " + permutect_training_dataset_truth_vcf else ""} \
            ~{if defined(permutect_test_dataset_truth_vcf) then "--permutect-test-truth " + permutect_test_dataset_truth_vcf else ""} \
            ~{m2_extra_args}

        m2_exit_code=$?

        ### GetPileupSummaries

        # If the variants for contamination and the intervals for this scatter don't intersect, GetPileupSummaries
        # throws an error.  However, there is nothing wrong with an empty intersection for our purposes; it simply doesn't
        # contribute to the merged pileup summaries that we create downstream.  We implement this via array outputs.
        # If the tool errors, no table is created and the glob yields an empty array.
        set +e

        if [[ ! -z "~{variants_for_contamination}" ]]; then
            gatk --java-options "-Xmx~{heap_size}m" GetPileupSummaries -R ~{ref_fasta} -I ~{tumor_reads} ~{"--interval-set-rule INTERSECTION -L " + intervals} \
                -V ~{variants_for_contamination} -L ~{variants_for_contamination} -O ~{tumor_pileups_table} ~{getpileupsummaries_extra_args}


            if [[ ! -z "~{normal_reads}" ]]; then
                gatk --java-options "-Xmx~{heap_size}m" GetPileupSummaries -R ~{ref_fasta} -I ~{normal_reads} ~{"--interval-set-rule INTERSECTION -L " + intervals} \
                    -V ~{variants_for_contamination} -L ~{variants_for_contamination} -O ~{normal_pileups_table} ~{getpileupsummaries_extra_args}
            fi
        fi

        # the script only fails if Mutect2 itself fails
        exit $m2_exit_code
    >>>

    runtime {
        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File unfiltered_vcf = "~{output_vcf}"
        File unfiltered_vcf_idx = "~{output_vcf_idx}"
        File output_bamOut = "~{bamout_name}"
        File stats = "~{output_stats}"
        File f1r2_counts = "~{f1r2_name}"
        Array[File] tumor_pileups = glob("*tumor-pileups.table")
        Array[File] normal_pileups = glob("*normal-pileups.table")
        File permutect_training_dataset = "~{training_dataset_name}"
        File permutect_test_dataset = "~{test_dataset_name}"
        File permutect_contigs_table = "~{contigs_table_name}"
        File permutect_read_groups_table = "~{read_groups_table_name}"
    }
}

task MergeVCFs {
    input {
      Array[File] input_vcfs
      Array[File] input_vcf_indices
      Boolean compress_vcfs
      String tumor_sample_name

      #runtime
      
      String gatk_docker
      Int cpu
      Int mem
      Int disk
      Int heap_size


    }

    String output_vcf = if compress_vcfs then tumor_sample_name + "merged.vcf.gz" else tumor_sample_name + "merged.vcf"
    String output_vcf_idx = output_vcf + if compress_vcfs then ".tbi" else ".idx"

    # using MergeVcfs instead of GatherVcfs so we can create indices
    # WARNING 2015-10-28 15:01:48 GatherVcfs  Index creation not currently supported when gathering block compressed VCFs.
    command <<<
        set -e

        #block for debugging file input problems
        ############################################################################################
        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################

        gatk --java-options "-Xmx~{heap_size}m" MergeVcfs -I ~{sep=' -I ' input_vcfs} -O ~{output_vcf}


    >>>

    runtime {
        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File merged_vcf = "~{output_vcf}"
        File merged_vcf_idx = "~{output_vcf_idx}"
    }
}

task MergeBamOuts {
    input {
      File ref_fasta
      File ref_fai
      File ref_dict
      Array[File]+ bam_outs
      String tumor_sample_name

      #runtime
      
      String gatk_docker
      Int cpu
      Int disk
      Int mem
      Int heap_size
    }

    String merged_bam = tumor_sample_name + "-merged.bam"
    String merged_bam_index = merged_bam + ".bai"

    command <<<
        # This command block assumes that there is at least one file in bam_outs.
        #  Do not call this task if len(bam_outs) == 0

        #block for debugging file input problems
        ############################################################################################
        set -euo pipefail

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################

        gatk --java-options "-Xmx~{heap_size}m" GatherBamFiles \
            -I ~{sep=" -I " bam_outs} -O unsorted.out.bam -R ~{ref_fasta}

        # We must sort because adjacent scatters may have overlapping (padded) assembly regions, hence
        # overlapping bamouts

        gatk --java-options "-Xmx~{heap_size}m" SortSam -I unsorted.out.bam \
            -O ~{merged_bam} --SORT_ORDER coordinate -VALIDATION_STRINGENCY LENIENT
        gatk --java-options "-Xmx~{heap_size}m" BuildBamIndex -I ~{merged_bam} -VALIDATION_STRINGENCY LENIENT
    >>>

    runtime {

        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File merged_bam_out = "~{merged_bam}"
        File merged_bam_out_index = "~{merged_bam_index}"
    }
}


task MergeStats {
    input {
      Array[File]+ stats
      #runtime
      
      String gatk_docker
      Int cpu
      Int mem
      Int disk
      Int heap_size
    }
    #define the heap space usage for java tools

    command <<<
        #block for debugging file input problems
        ############################################################################################
        set -euo pipefail

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################

        gatk --java-options "-Xmx~{heap_size}m" MergeMutectStats \
            -stats ~{sep=" -stats " stats} -O merged.stats
    >>>

    runtime {
        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File merged_stats = "merged.stats"
    }
}

task MergePileupSummaries {
    input {
      Array[File] input_tables
      String output_name
      File ref_dict
      
      String gatk_docker
      Int cpu
      Int mem
      Int disk
      Int heap_size
    }

    command <<<
        #block for debugging file input problems
        ############################################################################################
        set -euo pipefail

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################

        gatk --java-options "-Xmx~{heap_size}m" GatherPileupSummaries \
        --sequence-dictionary ~{ref_dict} \
        -I ~{sep=' -I ' input_tables} \
        -O ~{output_name}.tsv
    >>>

    runtime {
        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File merged_table = "~{output_name}.tsv"
    }
}

# Learning step of the orientation bias mixture model, which is the recommended orientation bias filter as of September 2018
task LearnReadOrientationModel {
    input {
      Array[File] f1r2_tar_gz
      
      String gatk_docker
        Int cpu
        Int disk
        Int mem
        Int heap_size
    }

    command <<<
        #block for debugging file input problems
        ############################################################################################
        set -euo pipefail

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################


        gatk --java-options "-Xmx~{heap_size}m" LearnReadOrientationModel \
            -I ~{sep=" -I " f1r2_tar_gz} \
            -O "artifact-priors.tar.gz"
    >>>

    runtime {

        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File artifact_prior_table = "artifact-priors.tar.gz"
    }

}

task CalculateContamination {
    input {
      String? intervals
      File tumor_pileups
      File? normal_pileups
      
      String gatk_docker
        Int cpu
        Int disk
        Int mem
        Int heap_size
    }

    command <<<
        #block for debugging file input problems
        ############################################################################################
        set -euo pipefail

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################

        gatk --java-options "-Xmx~{heap_size}m" CalculateContamination -I ~{tumor_pileups} \
        -O contamination.table --tumor-segmentation segments.table ~{if defined(normal_pileups) then "-matched " + normal_pileups else ""}
    >>>

    runtime {

        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File contamination_table = "contamination.table"
        File maf_segments = "segments.table"
    }
}

task Filter {
    input {
        File? intervals
        File ref_fasta
        File ref_fai
        File ref_dict
        File unfiltered_vcf
        File unfiltered_vcf_idx
        Boolean compress_vcfs
        File? mutect_stats
        File? artifact_priors_tar_gz
        File? contamination_table
        File? maf_segments
        String? m2_extra_filtering_args
        String tumor_sample_name

        #runtime
        
        String gatk_docker
        Int cpu
        Int disk
        Int mem
        Int heap_size
    }

    String output_vcf = if compress_vcfs then tumor_sample_name + "-filtered.vcf.gz" else tumor_sample_name + "-filtered.vcf"
    String output_vcf_idx = output_vcf + if compress_vcfs then ".tbi" else ".idx"
    
    parameter_meta{
      ref_fasta: {localization_optional: true}
      ref_fai: {localization_optional: true}
      ref_dict: {localization_optional: true}
    }

    command <<<
        #block for debugging file input problems
        ############################################################################################
        set -euo pipefail

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################

        gatk --java-options "-Xmx~{heap_size}m" FilterMutectCalls -V ~{unfiltered_vcf} \
            -R ~{ref_fasta} \
            -O ~{output_vcf} \
            ~{"--contamination-table " + contamination_table} \
            ~{"--tumor-segmentation " + maf_segments} \
            ~{"--ob-priors " + artifact_priors_tar_gz} \
            ~{"-stats " + mutect_stats} \
            --filtering-stats filtering.stats \
            ~{m2_extra_filtering_args}
    >>>

    runtime {

        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File filtered_vcf = "~{output_vcf}"
        File filtered_vcf_idx = "~{output_vcf_idx}"
        File filtering_stats = "filtering.stats"
    }
}

task FilterAlignmentArtifacts {
    input {
      File ref_fasta
      File ref_fai
      File ref_dict
      File input_vcf
      File input_vcf_idx
      File reads
      File reads_index
      Boolean compress_vcfs
      File realignment_index_bundle
      String? realignment_extra_args
      String tumor_sample_name

      #runtime
      
      String gatk_docker
      Int cpu
      Int disk
      Int mem
      Int heap_size
    }


    String output_vcf = if compress_vcfs then tumor_sample_name + "-filtered.vcf.gz" else tumor_sample_name + "-filtered.vcf"
    String output_vcf_idx = output_vcf + if compress_vcfs then ".tbi" else ".idx"

    #define the heap space usage for java tools

    parameter_meta{
      ref_fasta: {localization_optional: true}
      ref_fai: {localization_optional: true}
      ref_dict: {localization_optional: true}
      input_vcf: {localization_optional: true}
      input_vcf_idx: {localization_optional: true}
      reads: {localization_optional: true}
      reads_index: {localization_optional: true}
    }

    command <<<
        #block for debugging file input problems
        ############################################################################################
        set -euo pipefail

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################

        gatk --java-options "-Xmx~{heap_size}m" FilterAlignmentArtifacts \
            -R ~{ref_fasta} \
            -V ~{input_vcf} \
            -I ~{reads} \
            --bwa-mem-index-image ~{realignment_index_bundle} \
            ~{realignment_extra_args} \
            -O ~{output_vcf}
    >>>

    runtime {

        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File filtered_vcf = "~{output_vcf}"
        File filtered_vcf_idx = "~{output_vcf_idx}"
    }
}

task Concatenate {
    input {
        Array[File] input_files

        #runtime
        
        String gatk_docker
        Int cpu
        Int disk
        Int mem
    }

    command <<<
        #block for debugging file input problems
        ############################################################################################
        set -euo pipefail

        echo "===== INPUT ROOT ====="
        ls -lah /home/dnanexus/inputs || true

        echo "===== INPUT SUBDIRS ====="
        ls -lah /home/dnanexus/inputs/input* || true
        #############################################################################################

        cat ~{sep=' ' input_files} > output.txt
    >>>

    runtime {
        docker: gatk_docker
        cpu: cpu
        memory: mem + " GB"
        disks: "local-disk " + disk + " SSD"
    }

    output {
        File concatenated = "output.txt"
    }
}